[project]
name = "ffb24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.8.6",
    "dbt-duckdb>=1.8.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
